[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.8.16"

fs_permissions = [{access = "read", path = "."}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/", chainId = 5 }